### ISSUE TITLE
Contribute quotes for Hacktoberfest

### ISSUE THREAD

**Issue by Jack1q** [Jack1q/Quotecraft#1]

**Comment by ywalia01** [comment]
Hey, I'd like to work on this. Could you provide some more details
Thanks

**Comment by solonovamax** [comment]
This is probably something that could be done easily with an online API

**Comment by ywalia01** [comment]
Yup, that's what I was thinking. Thanks!

**Comment by solonovamax** [comment]
just an fyi, I'm not affiliated with the project

**Comment by ywalia01** [comment]
I just realised that lol

**Comment by Jack1q** [comment]
Hey all :)
Anyone interested in contributing quotes can simply add quotes to [life.csv](https://github.com/Jack1q/Quotecraft/blob/master/Quotecraft/src/com/gmail/jackdonofrio12/quotes/life.csv) or [motivation.csv](https://github.com/Jack1q/Quotecraft/blob/master/Quotecraft/src/com/gmail/jackdonofrio12/quotes/motivation.csv). 
Please follow the format of:
quote content, speaker

If you want to change anything else in the repo, like modify the plugin to make calls to an online quote API, you can make a PR and I'll happily take a look.
